#
# $ cat .env
#
#   PAPERMERGE__SECURITY__SECRET_KEY=123
#   PAPERMERGE__DATABASE__URL=sqlite:////<absolute path to sqlite3 file>
#
#   # For oauth2 based authentication
#   PAPERMERGE__AUTH__GOOGLE_CLIENT_ID=
#   PAPERMERGE__AUTH__GOOGLE_CLIENT_SECRET=

#
version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
     - "7000:80"
    environment:
      PAPERMERGE__SECURITY__SECRET_KEY: ${PAPERMERGE__SECURITY__SECRET_KEY}
    volumes:
      - ./db:/db
      - ./auth_server/:/auth_server_app/auth_server/
      - ./ui/node_modules:/app_ui/node_modules/
      - ./ui/src/:/app_ui/src/
      - ./ui/public/:/app_ui/public/
      - ./ui/tsconfig.json:/app_ui/tsconfig.json
