version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
     - "7000:80"
    environment:
      PAPERMERGE__SECURITY__SECRET_KEY: 123  # top secret
    volumes:
      - ./db:/db
      - ./auth_server/:/auth_server_app/auth_server/
      - ./ui/node_modules:/app_ui/node_modules/
      - ./ui/src/:/app_ui/src/
      - ./ui/public/:/app_ui/public/
      - ./ui/tsconfig.json:/app_ui/tsconfig.json
